name: Process Chrome OS recovery images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '21 1,7,13,19 * * *'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install requirements
        run: pip3 install -r scripts/requirements.txt

      - name: Generate Chrome/OS version maps
        run: python3 scripts/generate_chromeos2chrome_versionmap.py

      - name: Process latest recovery.json
        run: python3 scripts/process-latest-recovery.py

      - name: Analyze recovery images
        run: python3 scripts/analyze_image_details.py

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
