name: Process Chrome OS updates 

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '3,13,23,33,43,53 * * * *'

jobs:
  process-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install requirements
        run: pip3 install -r scripts/requirements.txt

      - name: Check for updates
        run: python3 scripts/check-for-updates.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git add data/*
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add updates changes [ci skip]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
